### PR TITLE
fix: Fix unappropriate stack trace issue on Node.js prior than v14

### LINKED ISSUE #702: Got TypeError flat is not a function on Node.js 10  supertest 6.1.1
Look like this update 02888268617e546fb087629ac773b207fc164bdd which uses `Array.flat` doesn't work in older Node.js 

So when a test doesn't pass, instead of showing proper error stack, its showing inappropriate error like this

```
TypeError: [err.toString(...),savedStack,"----",badStack].flat is not a function
```

### PR DESCRIPTION
**Pull request by ktutnik**
closes #702

### CODE REVIEW

File: lib/test.js [hunk 1]
```diff
@@ -80,7 +80,11 @@ function wrapAssertFn(assertFn) {
     var err = assertFn(res);
     if (err && err.stack) {
       badStack = err.stack.replace(err.message, '').split('\n').slice(1);
-      err.stack = [err.toString(), savedStack, '----', badStack].flat().join('\n');
+      err.stack = [err.toString()]
+        .concat(savedStack)
+        .concat('----')
+        .concat(badStack)
+        .join('\n');
```
Comment (niftylettuce) [inline lib/test.js:87]: Can you use `push` instead?  I believe it is much faster than `concat`.

**Review by niftylettuce — CHANGES_REQUESTED** [review]

File: lib/test.js (hunk 1 above)
Comment (ktutnik) [reply lib/test.js:87]: The idea of using `concat` is because the `savedStack` and `badStack` is an array.
push will require hack using `array.push.apply(array, savedStack)`. Ok with that?

**Comment by niftylettuce** [comment]
v6.1.2 released https://github.com/visionmedia/supertest/releases/tag/v6.1.2
